[build]
languages = ["python", "node"]

[phases.setup]
commands = [
  "echo Installing backend dependencies",
  "cd backend && python3 -m pip install --upgrade pip",
  "cd backend && python3 -m pip install -r requirements.txt",
  "echo Installing frontend dependencies",
  "cd frontend && npm install"
]

[phases.build]
commands = [
  "echo Building frontend",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python app.py"

[env]
PORT = "8000"
